site_name: Panduan Aplikasi Manajemen Pegawai
theme:
  name: material
  palette:
   
    # Palette toggle for light mode
    - scheme: default
      pimary: amber
      accent: amber
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: amber
      accent: amber
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

        # mengatur font 
  font:
    text: Open sans
    code: JetBrainse mono
 
    #icon
      logo: 
      favicon: 

      icon:
      admonotion:
        note: font awesome/solid/note.sticky
        abstrack: font awesome/solid/book
        info: font awesome/solid/circle.info
        tip: font awesome/solid/bullhorn
        succese: font awesome/solid/check
        question: font awesome/solid/circle-question
        warning: font awesome/solid/triangle-axclamation
        failur: font awesome/solid/bomb
        danger: font awesome/solid/skull
        bug: font awesome/solid/robot
        example: font awesome/solid/flask
        quote: font awesome/solid/quote.left
       
        features: 
          # - navigation.fonter
          # - navigation.

          markdown_extensions:
          - admonition
          - pyadownx.details
          - pyadownx.superfance
          # fitur
          - atr-list
          # keyboard
          - pyadownx.keys
  - pymdownx.arithmatex:
      generic: true

      plugins:
        - search

        # footer
        copyright: made with by kelompok 2 | &copy; 2025

        extra:
          generator: false 